//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.edu.upc.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimiento()
        {
            this.multa = new HashSet<multa>();
        }
    
        public int id { get; set; }
        public System.DateTime fechaprestamo { get; set; }
        public System.DateTime fechadevolucion { get; set; }
        public string estado { get; set; }
        public int ipad_id { get; set; }
        public int bibliotecario_id { get; set; }
        public int usuario_id { get; set; }
        public Nullable<System.DateTime> fechadevolucionreal { get; set; }
    
        public virtual bibliotecario bibliotecario { get; set; }
        public virtual ipad ipad { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<multa> multa { get; set; }
    }
}
